blueprint:
  name: TV Voice Assistant Sentences
  description: Control TVs with Voice Assistants
  domain: automation
  author: J.P. Naifeh
  input:
    tv_entity:
      name: TV
      selector:
        entity:
          filter:
            domain:
            - media_player
          multiple: false
mode: queued
max_exceeded: silent
variables:
  tv_entity_id: !input tv_entity
  tv_friendly_name: "{{ state_attr(tv_entity_id, 'friendly_name') }}"
triggers:
  - trigger: conversation
    command:
      - "{{ tv_friendly_name }} on"
    id: "on"
  - trigger: conversation
    command:
      - "{{ tv_friendly_name }} off"
    id: "off"
  - trigger: conversation
    command: 
      - "{{ tv_entity_id }}"
    id: "toggle"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - action: media_player.turn_on
            target:
              entity_id: !input tv_entity
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - action: media_player.turn_off
            target:
              entity_id: !input tv_entity
      - conditions:
          - condition: trigger
            id: "toggle"
        sequence:
          - if:
              - condition: state
                entity_id: !input tv_entity
                state: "on"
            then:
              - action: media_player.turn_off
                target:
                  entity_id: !input tv_entity
            else:
              - action: media_player.turn_on
                target:
                  entity_id: !input tv_entity